function [leafDir,leafNor,twigS,twigE] = sample_leaf_orientations(...
                                              CylinderParameters, ...
                                              leafParent, ...
                                              TargetDistributions, ...
                                              LeafProperties, ...
                                              TwigDirectionDistribution,...
                                              Phyllotaxis)

% Twig length limits
twigLengthLimits = LeafProperties.twigLengthLimits;

nLeavesTotal = size(leafParent,1);
leafDir = zeros(nLeavesTotal,3);
leafNor = zeros(nLeavesTotal,3);
twigS   = zeros(nLeavesTotal,3);
twigE   = zeros(nLeavesTotal,3);
iLeaf = 1;
for iCyl = 1:length(CylinderParameters.relative_height)
    % Number of leaves on cylinder
    nLeavesCyl = sum(leafParent == iCyl);
    if nLeavesCyl > 0
        % Cylinder structural variable coordinates
        svCoords = [CylinderParameters.relative_height(iCyl), ...
             CylinderParameters.relative_distance_along_subbranch(iCyl),...
             CylinderParameters.compass_direction(iCyl)];
        % Cylinder length
        len = CylinderParameters.length(iCyl);
        % Cylinder radius
        rad = CylinderParameters.radius(iCyl);
        % Cylinder axis
        axis = CylinderParameters.axis(iCyl,:) ...
               /norm(CylinderParameters.axis(iCyl,:));
        % Cylinder inclination angle
        inc = acos(dot(axis,[0 0 1]));
        % Cylinder azimuth angle (counterclockwise wrt. north direction)
        axisXY = [axis(1) axis(2) 0];
        axisXY = axisXY/norm(axisXY);
        if axis(1) <= 0
            az = dot(axisXY,[0 1 0]);
        else
            az = 2*pi - dot(axisXY,[0 1 0]);
        end
    
        % LOD distribution types and parameters
        dTypeLODinc = TargetDistributions.dTypeLODinc;
        dTypeLODaz  = TargetDistributions.dTypeLODaz;
        dParametersLODinc = TargetDistributions.fun_inc_params(...
                                                            svCoords(1),...
                                                            svCoords(2),...
                                                            svCoords(3));
        dParametersLODaz  = TargetDistributions.fun_az_params(...
                                                            svCoords(1),...
                                                            svCoords(2),...
                                                            svCoords(3));
        % Sample leaf orientation and twig coordinates
        [dir,nor,tws,twe] = fun_leaf_orientation(len,rad,inc,az, ...
                                              nLeavesCyl, ...
                                              twigLengthLimits, ...
                                              dTypeLODinc, ...
                                              dTypeLODaz, ...
                                              dParametersLODinc, ...
                                              dParametersLODaz, ...
                                              TwigDirectionDistribution,...
                                              Phyllotaxis);
        leafDir(iLeaf:(iLeaf+(nLeavesCyl-1)),:) = dir;
        leafNor(iLeaf:(iLeaf+(nLeavesCyl-1)),:) = nor;
        twigS(iLeaf:(iLeaf+(nLeavesCyl-1)),:) = ...
                              tws + CylinderParameters.start_point(iCyl,:);
        twigE(iLeaf:(iLeaf+(nLeavesCyl-1)),:) = ...
                              twe + CylinderParameters.start_point(iCyl,:);

        iLeaf = iLeaf + nLeavesCyl;
    end
end

end